version: '3.8'

services:
  bot:
    # build: . 
    # image: yolo_webapp-bot:latest
    image: ilya9kkk/tgbot:latest

    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - .:/app
    restart: unless-stopped
    command: python3 tgbot.py 

 
