name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # триггер для деплоя после пуша в main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Среда для выполнения (Ubuntu)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Copy files to Raspberry Pi
        uses: appleboy/scp-action@v0.1.3  # Копирование файлов на Raspberry Pi через SCP
        with:
          host: ${{ secrets.PI_HOST }}  # IP или домен Raspberry Pi
          username: ${{ secrets.PI_USER }}  # Имя пользователя на Raspberry Pi
          key: ${{ secrets.PI_SSH_KEY }}  # Приватный SSH ключ для подключения
          source: "."  # Откуда копируем (весь репозиторий)
          target: "~/yolo_webapp"  # Куда копируем на Raspberry Pi

      - name: Run Docker container on Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3  # Выполнение команд через SSH на Raspberry Pi
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd ~/yolo_webapp
            docker-compose down || true  # Останавливаем старый контейнер, если он существует
            docker-compose up -d --build  # Собираем и запускаем новый контейнер
